/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WRouteImport } from './routes/w'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WIndexRouteImport } from './routes/w/index'
import { Route as WWorkspaceIdRouteImport } from './routes/w/$workspaceId'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w/$workspaceId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WWorkspaceIdPProjectIdRouteImport } from './routes/w/$workspaceId/p/$projectId'
import { Route as WWorkspaceIdPProjectIdSetupRouteImport } from './routes/w/$workspaceId/p/$projectId/setup'

const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIndexRoute = WIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WRoute,
} as any)
const WWorkspaceIdRoute = WWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WRoute,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdPProjectIdRoute = WWorkspaceIdPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdPProjectIdSetupRoute =
  WWorkspaceIdPProjectIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => WWorkspaceIdPProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/w': typeof WRouteWithChildren
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/w/': typeof WIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRouteWithChildren
  '/w/$workspaceId/p/$projectId/setup': typeof WWorkspaceIdPProjectIdSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/w': typeof WIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRouteWithChildren
  '/w/$workspaceId/p/$projectId/setup': typeof WWorkspaceIdPProjectIdSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/w': typeof WRouteWithChildren
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/w/': typeof WIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRouteWithChildren
  '/w/$workspaceId/p/$projectId/setup': typeof WWorkspaceIdPProjectIdSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/w'
    | '/w/$workspaceId'
    | '/w/'
    | '/api/auth/$'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/w'
    | '/api/auth/$'
    | '/w/$workspaceId'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/setup'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/w'
    | '/w/$workspaceId'
    | '/w/'
    | '/api/auth/$'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  WRoute: typeof WRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/': {
      id: '/w/'
      path: '/'
      fullPath: '/w/'
      preLoaderRoute: typeof WIndexRouteImport
      parentRoute: typeof WRoute
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteImport
      parentRoute: typeof WRoute
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/p/$projectId': {
      id: '/w/$workspaceId/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/w/$workspaceId/p/$projectId'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/p/$projectId/setup': {
      id: '/w/$workspaceId/p/$projectId/setup'
      path: '/setup'
      fullPath: '/w/$workspaceId/p/$projectId/setup'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdSetupRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRoute
    }
  }
}

interface WWorkspaceIdPProjectIdRouteChildren {
  WWorkspaceIdPProjectIdSetupRoute: typeof WWorkspaceIdPProjectIdSetupRoute
}

const WWorkspaceIdPProjectIdRouteChildren: WWorkspaceIdPProjectIdRouteChildren =
  {
    WWorkspaceIdPProjectIdSetupRoute: WWorkspaceIdPProjectIdSetupRoute,
  }

const WWorkspaceIdPProjectIdRouteWithChildren =
  WWorkspaceIdPProjectIdRoute._addFileChildren(
    WWorkspaceIdPProjectIdRouteChildren,
  )

interface WWorkspaceIdRouteChildren {
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdPProjectIdRoute: typeof WWorkspaceIdPProjectIdRouteWithChildren
}

const WWorkspaceIdRouteChildren: WWorkspaceIdRouteChildren = {
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdPProjectIdRoute: WWorkspaceIdPProjectIdRouteWithChildren,
}

const WWorkspaceIdRouteWithChildren = WWorkspaceIdRoute._addFileChildren(
  WWorkspaceIdRouteChildren,
)

interface WRouteChildren {
  WWorkspaceIdRoute: typeof WWorkspaceIdRouteWithChildren
  WIndexRoute: typeof WIndexRoute
}

const WRouteChildren: WRouteChildren = {
  WWorkspaceIdRoute: WWorkspaceIdRouteWithChildren,
  WIndexRoute: WIndexRoute,
}

const WRouteWithChildren = WRoute._addFileChildren(WRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  WRoute: WRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
